#!/bin/sh

psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c "CREATE DATABASE checklist;"
psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c "CREATE USER ${CHECKLIST_USER-check} WITH ENCRYPTED PASSWORD '${CHECKLIST_PASSWORD-check}';"