version: '3'

services:
  db:
    image: postgres:11.1
    ports:
     - 5432:5432
    env_file: .env
    volumes:
       - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 28080:8080

volumes:
  db-data: