version: '3'

services:
  db:
    build: 
      context: ../../checklist-db/build
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: 
      context: ../../checklist-back/build
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env

  proxy:
    build: 
      context: ../../checklist-proxy/build
      dockerfile: Dockerfile
    depends_on:
      - app
    ports:
      - 7080:80
    
  adminer:
    image: adminer
    ports:
      - 28080:8080

volumes:
  db-data: