version: '3'

services:
  db:
    image: postgres:11.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=check
      - POSTGRES_USER=check
      - POSTGRES_DB=check
      - CHECKLIST_USER=app
      - CHECKLIST_PASSWORD=app
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build:
      context: ../../checklist/
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=check
      - POSTGRES_USER=check
      - POSTGRES_DB=check

  adminer:
    image: adminer
    ports:
      - 28080:8080

volumes:
  db-data: