export const FETCH_CATEGORY = 'FETCH_CATEGORY';
export const FETCHING_CATEGORY = 'FETCHING_CATEGORY';
export const RECEIVE_CATEGORY = 'RECEIVE_CATEGORY';
export const POSTING_CATEGORY = 'POSTING_CATEGORY';
export const POST_CATEGORY_SUCCESS = 'POST_CATEGORY_SUCCESS';
export const POST_CATEGORY_ERROR = 'POST_CATEGORY_ERROR';
export const NEW_CATEGORY = 'NEW_CATEGORY';


export const FETCH_PRODUCT = "FETCH_PRODUCT";

