export const FETCH_CATEGORY = 'FETCH_CATEGORY';
export const FETCHING_CATEGORY = 'FETCHING_CATEGORY';
export const RECEIVE_CATEGORY = 'RECEIVE_CATEGORY';

export const FETCH_PRODUCT = "FETCH_PRODUCT";